theme: jekyll-theme-minimal
title: Francisco S. Melo 
description: I'm an artificial intelligence researcher and educator working in problems of planning and learning under uncertainty.
logo: images/fmelo-bw.jpg
